name: CI
permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - Readme.md

jobs:
  sonar-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate SonarQube analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Check Quality Gate Status
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true  # Allows the pipeline to proceed even if SonarCloud fails  

  push:
    runs-on: ubuntu-latest
    needs: sonar-scan  # Wait until SonarQube scan is successful
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myfile:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update tag
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/myfile-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "chaudharivipul945@gmail.com"
          git config --global user.name "Jitu"
          git add helm/myfile-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push

